spring:
  application:
    name: hmsDemo
  datasource:
    url: jdbc:mysql://localhost:3306/hmsdemo
    username: root
    password: Vishal@2020
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect